# Uncomment this line to define a global platform for your project
# platform :ios, "7.0"

target "MultiLineUIPageControlDemo" do
    pod 'MultiLineUIPageControl', :git => 'git@github.com:luizalabs/MultiLineUIPageControl.git'
end